spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
        ddl-auto: update
  security:
    user:
      name: ivan
      password: password
server:
  port: 8443
  ssl:
    key-store: src/main/resources/mykeys.jks
    key-store-password: letmein
    key-password: letmein
logging:
  file:
    path: /var/logs/
    file: TacoCloud.log
  level:
    root: WARN
    org:
      springframework:
        security: WARN