spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
        ddl-auto: update
#    driver-class-name: org.postgresql.Driver
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL162Dialect
#     generate-unique-name: false
#     name: TacoCloud
#  main:
#      allow-bean-definition-overriding: true